version: '3.8'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: movies-db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  migrations:
    build:
      context: .
      dockerfile: Dockerfile.dev
    depends_on:
      - mysql
    environment:
      - DB_HOST=mysql
      - DB_USERNAME=root
      - DB_PASSWORD=rootpassword
      - DB_DATABASE=movies-db
      - TMDB_TOKEN=${TMDB_TOKEN}
    volumes:
      - ./src:/app/src
    command: npm run migration:run

  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    depends_on:
      - migrations
    environment:
      - DB_HOST=mysql
      - DB_USERNAME=root
      - DB_PASSWORD=rootpassword
      - DB_DATABASE=movies-db
      - TMDB_TOKEN=${TMDB_TOKEN}
    ports:
      - "8080:8080"
    volumes:
      - ./src:/app/src

volumes:
  mysql_data:
