version: '3.8'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: movies-db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  migrations:
    build:
      context: .
      dockerfile: Dockerfile.dev
    depends_on:
      - mysql
    env_file:
      - .env
    environment:
      - DB_HOST=mysql
      - DB_USERNAME=root
      - DB_PASSWORD=rootpassword
      - DB_DATABASE=movies-db
    volumes:
      - ./src:/app/src
    command: npm run migration:run

  redis:
    image: redis:7-alpine
    container_name: movie-api-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    depends_on:
      - migrations
      - redis
    env_file:
      - .env
    ports:
      - "8080:8080"
    volumes:
      - ./src:/app/src

volumes:
  mysql_data:
  redis_data:
